proj_path=$(shell pwd)/../..
makeproj_path=$(proj_path)/makeproject
include $(makeproj_path)/source.mk
include tests.mk

## Add main Entrance
main=test.cpp 
sources+=$(main)
exec=test

include last.mk
